_BASE_: "../../fastreid/configs/Base-SBS.yml"

SEED: 5

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True
    WITH_NL: True

DATASETS:
  NAMES: ("VehicleID",)
  TESTS: ("SmallVehicleID", "MediumVehicleID", "LargeVehicleID",)

SOLVER:
  AMP:
    ENABLED: True
  OPT: SGD
  BASE_LR: 0.01
  ETA_MIN_LR: 7.7e-5
  IMS_PER_BATCH: 64
  MAX_EPOCH: 40
  DELAY_EPOCHS: 20
  WARMUP_ITERS: 3000
  FREEZE_ITERS: 3000
  CHECKPOINT_PERIOD: 8

DATALOADER:
  SAMPLER_TRAIN: BalancedIdentitySampler
  NUM_INSTANCE: 4

TEST:
  EVAL_PERIOD: 4
  IMS_PER_BATCH: 64
  NUM_WORKERS: 0
  PIN_MEMORY: False

OUTPUT_DIR: "outputs/vehicleid_sbs_baseline_nl_amp64_seed5_k4_e40_20260422"
