_BASE_: "../../fastreid/configs/VeRi/sbs_R50-ibn.yml"

SEED: 4

MODEL:
  BACKBONE:
    WITH_NL: True

SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 64
  MAX_EPOCH: 60

DATALOADER:
  NUM_INSTANCE: 16

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 128

OUTPUT_DIR: "outputs/veri776_sbs_baseline_nl_amp64_seed4_20260421"
