_BASE_: "../fastreid/configs/VeRi/sbs_R50-ibn.yml"

MODEL:
  BACKBONE:
    NAME: build_resnet_lka_backbone
    WITH_NL: True
    LKA:
      ENABLED: True
      STAGES: ("layer4",)
      GAMMA_INIT: 1e-6

SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 64
  MAX_EPOCH: 60

DATALOADER:
  NUM_INSTANCE: 16

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 128

OUTPUT_DIR: "outputs/veri_r50ibn_lka_s3a_nl_amp64_v1_20260412"
